# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Flickr-Simple
version:      0.01
version_from: lib/Flickr/Simple.pm
installdirs:  site
requires:
    Flickr::API:                   0.08
    Log::Agent:                    0.307
    Storable:                      2.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
